name: .NET

on:
  pull_request:
    branches: [ master ] 
  push: 

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]

    steps:
    - name: set mac R_HOME
      if: matrix.os == 'macOS-latest'
      env: 
        R_HOME: /Library/Frameworks/R.framework/Resources 
    - name: set ubuntu R_HOME
      if: matrix.os == 'ubuntu-latest'
      env: 
        R_HOME: /usr/local/bin/R
    - name: set windows R_HOME
      if: matrix.os == 'windows-latest'
      env: 
        R_HOME: C:\R
    - name: verify R
      run: Rscript -e '1+1'
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      name: Setup R environment
      with:
          r-version: '4.1.1'
    
    - name: find home
      run: |
          R --print-home
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore tool dependencies
      run: dotnet tool restore
    - name: Restore paket dependencies
      run: dotnet paket restore
    - name: Restore dependencies
      run: dotnet restore RProvider.sln
    - name: Restore dependencies
      run: dotnet restore RProvider.Tests.sln
    - name: Build
      run: dotnet fake build -t All
